### ISSUE TITLE
write flag errors on Amazon Linux

### ISSUE THREAD

**Issue by sailorwoo** [conortm/ghkeys#2]
When using -write on Amazon Linux I get a bad file descriptor error

[pubcentral@ip-10-6-2-57 ~]$ /usr/local/ghkeys/ghkeys -config="/usr/local/ghkeys/config.yml" -write pubcentral
2015/05/18 17:58:32 write /home/pubcentral/.ssh/authorized_keys: bad file descriptor

**Comment by conortm** [comment]
@sailorwoo Please try with [v0.0.3](https://github.com/conortm/ghkeys/releases/tag/v0.0.3). Thanks!

**Comment by conortm** [comment]
@sailorwoo The issue was with the cross-compiling tool I was using on my mac. I've re-compiled on an Amazon Linux box and tested. Should be good to go!

Please try new binary attached to [v0.0.3](https://github.com/conortm/ghkeys/releases/tag/v0.0.3). Thanks!

**Comment by conortm** [comment]
I got email confirmation from @sailorwoo that the new build resolved this issue. Closing!
